//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API_Editora
{
    using System;
    using System.Collections.Generic;
    
    public partial class livro_autor
    {
        public int Id { get; set; }
        public int id_livro { get; set; }
        public int id_autor { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Livros Livros { get; set; }
    }
}
